[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "aiorethink"
version = "0.2.2rc0"
description = "aiorethink is a fairly comprehensive but easy-to-use asyncio-enabled Object Document Mapper for RethinkDB"
readme = "README.rst"
authors = []
packages = [{include = "aiorethink"}]

[tool.poetry.dependencies]
python = ">=3.11"
cachetools = "6.0.0b4"
inflection = ">=0.5.1"
rethinkdb = ">=2.4.10.post1"

[tool.poetry.group.dev.dependencies]
sphinx = "*"
sphinx-autobuild = "*"
wheel = "*"
twine = "*"

[tool.poetry.group.test.dependencies]
coverage = "7.4.3"
pytest = ">=8.3.5"
pytest-asyncio = "0.26.0"
pytest-cov = "4.1.0"
pytest-timeout = "2.4.0"
tox = ">=4.26.0"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "auto"
