[tox]
envlist = py311
isolated_build = True
requires = poetry>=1.0.0

[testenv]
skip_install = true
allowlist_externals = poetry
commands =
    poetry install --with test
    poetry run pytest --cov=aiorethink --durations=10 tests/
