---
# Environment for ReadTheDocs

name: aiorethink-docs
dependencies:
- openssl
- pip
- python=3.11
- readline
- setuptools
- sqlite
- tk
- wheel
- xz
- zlib
- pip:
  - rethinkdb
  - inflection
  - cachetools==6.0.0b4
  - sphinx
  - sphinx-autobuild
